title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go mod tidy
  - go mod vendor
  after:
  - ./dagger-cf run -u "www.cachecha.com"
  - ./dagger-cf service -u "m3u8.cachecha.com" -to_host yes
  exit:
  - echo "ddd"
link: https://github.com/midoks/zzz
